apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: echo-server
          image: sekretaria/echo-server:0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: AUTHOR
              valueFrom:
                configMapKeyRef:
                  name: echo-server-config
                  key: AUTHOR
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
