FROM mcr.microsoft.com/devcontainers/python:3.12-bookworm

RUN pip install \
      ansible==9.2.0 \
      ansible-runner==2.3.5 \
      ansible-compat==4.1.11 \
      ansible-lint==24.2.0 \
      dnspython==2.6.1 \
      GitPython==3.1.42 \
      requests==2.31.0
