apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: echo-server
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: AUTHOR
              valueFrom:
                configMapKeyRef:
                  name: echo-server-config
                  key: AUTHOR
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 15
